(() => {
  "use strict";

  const $ = (selector) => document.querySelector(selector);
  const state = { orders: [], settings: {}, detail: null, selected: new Set(), summaryFilter: "", toastTimer: null, lastSelectedOrderNo: null };
  const reminderModes = [["UNSCHEDULED", "未安排提醒"], ["TODAY", "今天处理（网页）"], ["TOMORROW", "明天处理（网页）"], ["LONG_TERM", "长期提醒（邮件）"]].map(([value, label]) => ({ value, label }));
  const reminderModeNames = Object.fromEntries(reminderModes.map((option) => [option.value, option.label]));
  const terminalStages = new Set(["OVERSELL_CUSTOMER_REFUNDED", "COMPLETED"]);
  const lifecycleClientId = sessionStorage.getItem("order-reminder-client-id") || (window.crypto?.randomUUID ? window.crypto.randomUUID() : `${Date.now()}-${Math.random()}`);
  sessionStorage.setItem("order-reminder-client-id", lifecycleClientId);
  let lifecycleTimer;

  function sendClientHeartbeat(active = true) { const body = JSON.stringify({ client_id: lifecycleClientId, active }); if (!active && navigator.sendBeacon) { navigator.sendBeacon("/api/client/heartbeat", new Blob([body], { type: "application/json" })); return; } fetch("/api/client/heartbeat", { method: "POST", headers: { "Content-Type": "application/json" }, body, keepalive: !active }).catch(() => {}); }
  function startClientLifecycle() { sendClientHeartbeat(); lifecycleTimer = window.setInterval(() => sendClientHeartbeat(), 3000); window.addEventListener("pagehide", () => { window.clearInterval(lifecycleTimer); sendClientHeartbeat(false); }, { once: true }); }
  async function api(path, options = {}) { const headers = { ...(options.headers || {}) }; if (options.body && !(options.body instanceof FormData) && !headers["Content-Type"]) headers["Content-Type"] = "application/json"; const response = await fetch(path, { ...options, headers, cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || body.message || `请求失败（${response.status}）`); return body; }
  function setText(selector, value) { $(selector).textContent = value == null || value === "" ? "—" : String(value); }
  function formatDate(value) { return value ? String(value).replace("T", " ").replace(/\+08:00$/, "").slice(0, 16) : "—"; }
  function inputDate(value) { return value ? String(value).replace("+08:00", "").slice(0, 16) : ""; }
  function apiDate(value) { return value ? value.replace("T", " ").slice(0, 16) : null; }
  function dateKey(value) { return value ? String(value).slice(0, 10) : ""; }
  function shanghaiToday() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai" }).format(new Date()); }
  function addCalendarDays(value, days) { if (!value) return ""; const date = new Date(`${value}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
  function quickDeadlineInput(mode) { const date = mode === "TODAY" ? shanghaiToday() : addCalendarDays(shanghaiToday(), 1); return `${date}T${mode === "TODAY" ? "18:00" : "11:00"}`; }
  function displayDeadline(order) { const value = inputDate(order.deadline_override_at || order.deadline_at); if (!["TODAY", "TOMORROW"].includes(order.reminder_mode) || !value.endsWith("23:59")) return value; return `${dateKey(value)}T${order.reminder_mode === "TODAY" ? "18:00" : "11:00"}`; }
  function isCompleted(order) { return terminalStages.has(order.stage); }
  function hasCustomStage(order) { return String(order.custom_stage ?? "").trim().length > 0; }
  function hasProcessingDeadline(order) { return String(order.deadline_override_at ?? order.deadline_at ?? "").trim().length > 0; }
  function isUnprocessed(order) { return !isCompleted(order) && (!hasCustomStage(order) || !hasProcessingDeadline(order)); }
  function orderDeadline(order) { return order.deadline_override_at || order.deadline_at || ""; }
  function sortOrdersByDeadline(orders) { return [...orders].sort((a, b) => { const aDeadline = orderDeadline(a); const bDeadline = orderDeadline(b); if (!aDeadline && bDeadline) return -1; if (aDeadline && !bDeadline) return 1; if (!aDeadline && !bDeadline) return 0; return String(bDeadline).localeCompare(String(aDeadline)); }); }
  function displayedOrders() { const rows = filteredOrders(); return [...sortOrdersByDeadline(rows.filter((order) => !isCompleted(order))), ...sortOrdersByDeadline(rows.filter(isCompleted))]; }
  function stageName(order) { return isCompleted(order) ? "处理完成" : order.custom_stage || "未填写处理阶段"; }
  function modeName(value) { return reminderModeNames[value] || value || "未安排提醒"; }
  const customerNoteLabel = "客服备注";
  function riskName(value) { return ({ NORMAL: "正常", OVERDUE_RISK: "日期有风险", OVERDUE: "已逾期" })[value] || value || "正常"; }
  function issueName(value) { return ({ MISSING_ARRIVAL: "缺少处理截止", DATE_CONFLICT: "日期冲突", NONE: "无" })[value] || value || "—"; }
  function showToast(message, kind = "normal") { const toast = $("#toast"); toast.textContent = message; toast.className = `toast ${kind}`; toast.hidden = false; window.clearTimeout(state.toastTimer); state.toastTimer = window.setTimeout(() => { toast.hidden = true; }, 4200); }
  function copyOrderNos(orderNos) {
    const values = orderNos.filter(Boolean);
    if (!values.length) return;
    if (!navigator.clipboard?.writeText) { showToast("复制失败，请手动选择订单号", "error"); return; }
    navigator.clipboard.writeText(values.join(" ")).then(() => showToast("已复制 " + values.length + " 条订单号")).catch(() => showToast("复制失败，请手动选择订单号", "error"));
  }
  function setBusy(button, busy) { if (button) { button.disabled = busy; button.dataset.busy = busy ? "true" : "false"; } }
  function isUnfinished(order) { return !isCompleted(order); }
  function dueToday(order) { return isUnfinished(order) && dateKey(order.deadline_override_at || order.deadline_at) === shanghaiToday(); }
  function isOverdue(order) { return isUnfinished(order) && order.risk === "OVERDUE"; }
  function summaryMatches(order) { if (state.summaryFilter === "TOTAL") return isUnfinished(order); if (state.summaryFilter === "TODAY") return dueToday(order); if (state.summaryFilter === "TOMORROW") return isUnfinished(order) && dateKey(order.deadline_override_at || order.deadline_at) === addCalendarDays(shanghaiToday(), 1); if (state.summaryFilter === "LONG_TERM") return isUnfinished(order) && order.reminder_mode === "LONG_TERM"; if (state.summaryFilter === "OVERDUE") return isOverdue(order); if (state.summaryFilter === "UNPROCESSED") return isUnprocessed(order); return true; }
  function filteredOrders() { const search = $("#search-input").value.trim().toLowerCase(); const risk = $("#risk-filter").value; const rows = state.orders.filter((order) => { const searchable = [order.order_no, order.platform_user_name, order.consignee_name, order.operator_note, order.custom_stage].join(" ").toLowerCase(); return summaryMatches(order) && (!search || searchable.includes(search)) && (!risk || order.risk === risk); }); return [...sortOrdersByDeadline(rows.filter((order) => !isCompleted(order))), ...sortOrdersByDeadline(rows.filter(isCompleted))]; }
  function renderSummary() { const unfinished = state.orders.filter(isUnfinished); setText("#summary-total", unfinished.length); setText("#summary-today", unfinished.filter(dueToday).length); setText("#summary-tomorrow", unfinished.filter((order) => dateKey(order.deadline_override_at || order.deadline_at) === addCalendarDays(shanghaiToday(), 1)).length); setText("#summary-long-term", unfinished.filter((order) => order.reminder_mode === "LONG_TERM").length); setText("#summary-overdue", unfinished.filter(isOverdue).length); setText("#summary-unprocessed", state.orders.filter(isUnprocessed).length); document.querySelectorAll("[data-summary-filter]").forEach((card) => { const active = card.dataset.summaryFilter === state.summaryFilter; card.classList.toggle("is-active", active); card.setAttribute("aria-pressed", String(active)); }); }
  function updateSelectionUI() { $("#bulk-stage-save").disabled = state.selected.size === 0; const rows = filteredOrders(); const visibleSelected = rows.filter((order) => state.selected.has(order.order_no)).length; $("#selection-count").textContent = state.selected.size ? `已选择 ${state.selected.size} 条` : "未选择"; ["#delete-selected", "#copy-selected", "#quick-today", "#quick-tomorrow", "#quick-long-term", "#quick-unscheduled", "#quick-complete"].forEach((selector) => { $(selector).disabled = state.selected.size === 0; }); const selectAll = $("#select-all"); selectAll.checked = rows.length > 0 && visibleSelected === rows.length; selectAll.indeterminate = visibleSelected > 0 && visibleSelected < rows.length; }
  function resizeStageInput(input) { input.style.height = "auto"; input.style.height = input.scrollHeight + "px"; }
  function renderStageEditor(order) {
    if (isCompleted(order)) { const completed = document.createElement("span"); completed.className = "completed-stage-label"; completed.textContent = "处理完成"; return completed; }
    const input = document.createElement("textarea"); input.className = "custom-stage-input"; input.rows = 1; input.maxLength = 200; input.value = order.custom_stage || ""; input.placeholder = "填写当前处理阶段"; input.dataset.customStageOrder = order.order_no; input.dataset.previousCustomStage = order.custom_stage || ""; input.title = "填写 " + order.order_no + " 的处理阶段"; input.addEventListener("input", () => resizeStageInput(input)); requestAnimationFrame(() => resizeStageInput(input)); return input;
  }  function renderOrderRows(body, rows) {
    body.replaceChildren();
    rows.forEach((order) => {
      const row = document.createElement("tr"); row.dataset.orderNo = order.order_no; row.tabIndex = 0;
      const cell = (value, className = "") => { const node = document.createElement("td"); node.className = className; node.textContent = value == null || value === "" ? "—" : String(value); return node; };
      const checkCell = document.createElement("td"); checkCell.className = "row-check-cell"; const checkbox = document.createElement("input"); checkbox.type = "checkbox"; checkbox.className = "row-checkbox"; checkbox.checked = state.selected.has(order.order_no); checkbox.dataset.orderNo = order.order_no; checkbox.setAttribute("aria-label", `选择 ${order.order_no}`); checkCell.append(checkbox); row.append(checkCell);
      const orderCell = document.createElement("td"); orderCell.className = "order-cell"; const number = document.createElement("button"); number.type = "button"; number.className = "order-no-button"; number.dataset.copyOrder = order.order_no; number.title = "点击复制订单号"; number.textContent = order.order_no || "—"; const copyMark = document.createElement("span"); copyMark.className = "copy-mark"; copyMark.setAttribute("aria-hidden", "true"); copyMark.textContent = "⧉"; number.append(copyMark); const buyer = document.createElement("span"); buyer.textContent = order.consignee_name || order.platform_user_name || "未填写收件人"; orderCell.append(number, buyer); row.append(orderCell, cell(`${order.platform_user_name || "未命名店铺"} / ${order.warehouse_name || "未分配仓库"}`, "muted-cell"));
      const stageCell = document.createElement("td"); stageCell.className = "stage-cell"; stageCell.append(renderStageEditor(order)); const noteCell = cell(order.operator_note || "—", "note-cell"); noteCell.setAttribute("aria-label", customerNoteLabel); row.append(stageCell, noteCell, cell(formatDate(order.deadline_override_at || order.deadline_at), "date-cell deadline-cell"), cell(modeName(order.reminder_mode), "mode-cell"));
      const riskCell = document.createElement("td"); const risk = document.createElement("span"); risk.className = `risk-badge risk-${String(order.risk || "NORMAL").toLowerCase()}`; risk.textContent = riskName(order.risk); riskCell.append(risk); row.append(riskCell);
      body.append(row);
    });
  }
  function renderTable() {
    const rows = filteredOrders();
    const unfinishedRows = sortOrdersByDeadline(rows.filter((order) => !isCompleted(order)));
    const completedRows = sortOrdersByDeadline(rows.filter(isCompleted));
    renderOrderRows($("#order-table-body"), unfinishedRows);
    renderOrderRows($("#completed-order-table-body"), completedRows);
    $("#result-count").textContent = `${rows.length} 条记录`;
    $("#completed-orders-count").textContent = completedRows.length;
    $("#completed-orders-section").hidden = completedRows.length === 0;
    $("#order-table").hidden = unfinishedRows.length === 0;
    const empty = $("#empty-state"); empty.hidden = rows.length !== 0; $("#empty-title").textContent = state.orders.length ? "没有匹配的订单" : "暂无订单记录"; $("#empty-copy").textContent = state.orders.length ? "调整筛选条件，或清空搜索词后再试。" : "导入 ERP 导出的 Excel 后，订单会出现在这里。"; $("#empty-import").hidden = Boolean(state.orders.length); updateSelectionUI();
  }
  async function loadOrders() { $("#loading-state").hidden = false; try { const data = await api("/api/orders?limit=500"); state.orders = data.orders || []; const existing = new Set(state.orders.map((order) => order.order_no)); state.selected = new Set([...state.selected].filter((orderNo) => existing.has(orderNo))); renderSummary(); renderTable(); $("#service-status").textContent = "本机服务运行中"; } catch (error) { $("#service-status").textContent = "服务连接异常"; showToast(error.message, "error"); } finally { $("#loading-state").hidden = true; } }
  function explanation(order) { if (order.reminder_mode === "TODAY") return "今天处理只显示网页提醒，默认截止时间为今天 18:00，也可以手动修改。"; if (order.reminder_mode === "TOMORROW") return "明天处理只显示网页提醒，默认截止时间为明天 11:00，也可以手动修改。"; if (order.reminder_mode === "UNSCHEDULED") return "当前未安排提醒；日常订单可直接设为今天或明天处理。"; if (order.deadline_issue === "MISSING_ARRIVAL") return "还没有设置处理截止时间，长期提醒暂不生成。请填写截止时间后保存。"; if (order.deadline_issue === "DATE_CONFLICT") return "日期存在冲突，请手动设置处理截止时间。"; if (order.deadline_rule === "MANUAL") return `当前使用手动截止 ${formatDate(order.deadline_override_at)}；邮件按这个准确时间发送。`; return "长期提醒只在手动设置的处理截止时间发送一封邮件。"; }
  function renderDetail(detail) { const order = detail.order; state.detail = order; $("#drawer-title").textContent = order.order_no || "订单详情"; $("#drawer-subtitle").textContent = `${order.platform_user_name || "未命名店铺"} · ${order.consignee_name || "未填写收件人"}`; $("#detail-stage").textContent = stageName(order); $("#detail-status-input").value = isCompleted(order) ? "COMPLETED" : "IN_PROGRESS"; const risk = $("#detail-risk"); risk.textContent = riskName(order.risk); risk.className = `risk-badge risk-${String(order.risk || "NORMAL").toLowerCase()}`; $("#detail-rule").textContent = issueName(order.deadline_issue) + (order.deadline_rule && order.deadline_rule !== "NONE" ? ` · ${order.deadline_rule}` : ""); $("#detail-date-explanation").textContent = explanation(order); $("#reminder-mode-input").value = reminderModeNames[order.reminder_mode] ? order.reminder_mode : "UNSCHEDULED"; $("#deadline-override-input").value = displayDeadline(order); $("#custom-stage-input").value = order.custom_stage || ""; $("#tracking-input").value = order.actual_tracking_number || ""; $("#exception-note").value = order.processing_note || ""; $("#tracking-status").textContent = order.return_confirmed_at ? `已于 ${formatDate(order.return_confirmed_at)} 确认回传店铺` : order.actual_tracking_number ? "已有实际物流单号，等待确认回传" : "尚未取得实际物流单号"; $("#detail-erp-status").textContent = order.erp_status || ""; setText("#detail-platform", `${order.platform_user_name || "—"} / ${order.platform_seller_id || "—"}`); setText("#detail-warehouse", order.warehouse_name); setText("#detail-consignee", order.consignee_name); setText("#detail-country", order.consignee_country_name); setText("#detail-shipping", order.shipping_method_name_cn || order.shipping_method_name_en); setText("#detail-erp-tracking", order.erp_tracking_number); const resultSelect = $("#exception-result"); resultSelect.replaceChildren(); const blank = document.createElement("option"); blank.value = ""; blank.textContent = "选择结果"; resultSelect.append(blank); const results = state.settings.processing_results?.length ? state.settings.processing_results : ["取消", "等待补货", "继续等待"]; results.forEach((value) => { const option = document.createElement("option"); option.value = value; option.textContent = value; resultSelect.append(option); }); resultSelect.value = order.processing_result || ""; renderReminders(detail.reminders || []); renderHistory(detail.activity || []); updateDetailControls(order); const alert = $("#detail-alert"); alert.hidden = !["MISSING_ARRIVAL", "DATE_CONFLICT"].includes(order.deadline_issue); alert.textContent = order.deadline_issue === "MISSING_ARRIVAL" ? "长期提醒请先设置处理截止时间；日常订单可直接设为今天或明天。" : "日期存在冲突，请手动设置处理截止时间。"; }
  function updateDetailControls(order) { const completed = isCompleted(order); ["#save-dates", "#save-tracking", "#confirm-return", "#complete-exception", "#reminder-mode-input"].forEach((selector) => { $(selector).disabled = completed; }); $("#save-custom-stage").disabled = false; $("#detail-status-input").disabled = false; $("#confirm-return").disabled = completed || !order.actual_tracking_number; }
  function renderReminders(reminders) { const list = $("#detail-reminders"); list.replaceChildren(); if (!reminders.length) { const empty = document.createElement("span"); empty.className = "muted"; empty.textContent = "还没有生成提醒事件"; list.append(empty); return; } reminders.slice(0, 8).forEach((event) => { const item = document.createElement("div"); item.className = "reminder-item"; const label = document.createElement("strong"); label.textContent = ({ PROCESS_DAY: "处理日", ARRIVAL_EVE: "到货前一天", ARRIVAL_DAY: "到货当天", OVERDUE: "逾期" })[event.event_type] || event.event_type; const meta = document.createElement("span"); meta.textContent = `${formatDate(event.scheduled_at)} · ${event.status || "PENDING"}`; item.append(label, meta); list.append(item); }); }
  function renderHistory(history) { const list = $("#detail-history"); list.replaceChildren(); if (!history.length) { const empty = document.createElement("li"); empty.className = "muted"; empty.textContent = "暂无操作记录"; list.append(empty); return; } history.slice(0, 12).forEach((entry) => { const item = document.createElement("li"); const action = document.createElement("strong"); action.textContent = entry.action || "操作"; const meta = document.createElement("span"); meta.textContent = `${formatDate(entry.created_at)} · ${entry.actor || "本机"}`; item.append(action, meta); list.append(item); }); }
  async function openOrder(orderNo) { try { const detail = await api(`/api/orders/${encodeURIComponent(orderNo)}`); $("#order-drawer").classList.add("open"); $("#order-drawer").setAttribute("aria-hidden", "false"); $("#drawer-backdrop").hidden = false; document.body.classList.add("drawer-open"); renderDetail(detail); $("#drawer-close").focus(); } catch (error) { showToast(error.message, "error"); } }
  function closeDrawer() { $("#order-drawer").classList.remove("open"); $("#order-drawer").setAttribute("aria-hidden", "true"); $("#drawer-backdrop").hidden = true; document.body.classList.remove("drawer-open"); state.detail = null; }
  function openSettings() { $("#settings-dialog").hidden = false; document.body.classList.add("modal-open"); $("#setting-smtp-host").focus(); }
  function closeSettings() { $("#settings-dialog").hidden = true; document.body.classList.remove("modal-open"); }
  function renderSettings() { const settings = state.settings; $("#setting-windows").checked = settings.windows_notifications_enabled !== false; $("#setting-email").checked = settings.email_enabled === true; $("#setting-smtp-host").value = settings.smtp_host || "smtp.qq.com"; $("#setting-smtp-port").value = settings.smtp_port || 465; $("#setting-smtp-username").value = settings.smtp_username || ""; $("#setting-recipients").value = (settings.recipients || []).join(", "); $("#setting-results").value = (settings.processing_results || []).join(", "); }
  async function loadSettings() { try { state.settings = await api("/api/settings"); renderSettings(); } catch (error) { showToast(error.message, "error"); } }
  async function saveSettings(event) { event.preventDefault(); const button = $("#settings-form button[type=submit]"); setBusy(button, true); const patch = { windows_notifications_enabled: $("#setting-windows").checked, email_enabled: $("#setting-email").checked, smtp_host: $("#setting-smtp-host").value.trim(), smtp_port: Number($("#setting-smtp-port").value), smtp_username: $("#setting-smtp-username").value.trim(), recipients: $("#setting-recipients").value.split(",").map((item) => item.trim()).filter(Boolean), processing_results: $("#setting-results").value.split(",").map((item) => item.trim()).filter(Boolean) }; const secret = $("#setting-smtp-secret").value; if (secret) patch.smtp_authorization_code = secret; try { state.settings = await api("/api/settings", { method: "PATCH", body: JSON.stringify(patch) }); $("#setting-smtp-secret").value = ""; $("#settings-feedback").textContent = "已保存"; showToast("提醒设置已保存"); } catch (error) { $("#settings-feedback").textContent = error.message; showToast(error.message, "error"); } finally { setBusy(button, false); } }
  async function deleteOrders(orderNos) { const unique = [...new Set(orderNos)]; if (!unique.length) return; const label = unique.length === 1 ? `订单 ${unique[0]}` : `${unique.length} 条订单`; if (!window.confirm(`确定永久删除${label}吗？删除后订单及提醒记录不可恢复。`)) return; try { const result = await api("/api/orders", { method: "DELETE", body: JSON.stringify({ order_nos: unique }) }); state.selected = new Set([...state.selected].filter((orderNo) => !unique.includes(orderNo))); showToast(`已删除 ${result.deleted} 条订单`); await loadOrders(); } catch (error) { showToast(error.message, "error"); } }
  async function importWorkbook(event) { const file = event.target.files[0]; if (!file) return; const button = $("#import-trigger"); setBusy(button, true); const form = new FormData(); form.append("file", file); try { const result = await api("/api/import", { method: "POST", headers: {}, body: form }); showToast(`导入完成：新增 ${result.added}，更新 ${result.updated}，重复 ${result.duplicates || 0}`); await loadOrders(); } catch (error) { showToast(error.message, "error"); } finally { event.target.value = ""; setBusy(button, false); } }
  async function refreshOpenOrder(orderNo) { await loadOrders(); await openOrder(orderNo); }
  async function saveDates() { const button = $("#save-dates"); setBusy(button, true); try { const orderNo = state.detail.order_no; const mode = $("#reminder-mode-input").value; const deadlineInput = $("#deadline-override-input").value; const fallbackDate = mode === "TODAY" ? shanghaiToday() : mode === "TOMORROW" ? addCalendarDays(shanghaiToday(), 1) : ""; const payload = { reminder_mode: mode }; if (mode === "TODAY" || mode === "TOMORROW") payload.process_date = dateKey(deadlineInput) || fallbackDate; if (mode !== "UNSCHEDULED") payload.deadline_override_at = apiDate(deadlineInput); await api(`/api/orders/${encodeURIComponent(orderNo)}`, { method: "PATCH", body: JSON.stringify(payload) }); showToast("提醒与截止时间已保存"); await refreshOpenOrder(orderNo); } catch (error) { showToast(error.message, "error"); } finally { setBusy(button, false); } }
  async function saveCustomStage() { const button = $("#save-custom-stage"); const customStage = $("#custom-stage-input").value.trim(); const status = $("#detail-status-input").value; if (status !== "COMPLETED" && !customStage) { showToast("请先填写自定义处理阶段", "error"); $("#custom-stage-input").focus(); return; } setBusy(button, true); try { const orderNo = state.detail.order_no; await api(`/api/orders/${encodeURIComponent(orderNo)}`, { method: "PATCH", body: JSON.stringify({ stage: status === "COMPLETED" ? "COMPLETED" : "CUSTOM_STAGE", custom_stage: customStage || null }) }); showToast(status === "COMPLETED" ? "订单已标记为处理完成" : "自定义处理阶段已保存"); await refreshOpenOrder(orderNo); } catch (error) { showToast(error.message, "error"); } finally { setBusy(button, false); } }
  async function saveInlineCustomStage(input) { const customStage = input.value.trim(); const previous = input.dataset.previousCustomStage || ""; if (!customStage) { input.value = previous; showToast("请填写自定义处理阶段", "error"); return; } setBusy(input, true); try { const result = await api(`/api/orders/${encodeURIComponent(input.dataset.customStageOrder)}`, { method: "PATCH", body: JSON.stringify({ custom_stage: customStage }) }); const index = state.orders.findIndex((order) => order.order_no === input.dataset.customStageOrder); if (index >= 0) state.orders[index] = result.order; showToast("自定义处理阶段已保存"); renderSummary(); renderTable(); } catch (error) { input.value = previous; showToast(error.message, "error"); } finally { setBusy(input, false); } }
  async function applyModeToSelected(mode) { const orderNos = [...state.selected]; if (!orderNos.length) return; const processDate = mode === "TODAY" ? shanghaiToday() : mode === "TOMORROW" ? addCalendarDays(shanghaiToday(), 1) : undefined; ["#quick-today", "#quick-tomorrow", "#quick-long-term", "#quick-unscheduled"].forEach((selector) => setBusy($(selector), true)); try { await Promise.all(orderNos.map((orderNo) => api(`/api/orders/${encodeURIComponent(orderNo)}`, { method: "PATCH", body: JSON.stringify({ reminder_mode: mode, ...(processDate ? { process_date: processDate } : {}) }) }))); showToast(`已将 ${orderNos.length} 条订单设为${modeName(mode)}`); await loadOrders(); } catch (error) { showToast(error.message, "error"); } finally { ["#quick-today", "#quick-tomorrow", "#quick-long-term", "#quick-unscheduled"].forEach((selector) => setBusy($(selector), false)); updateSelectionUI(); } }
  async function applyCustomStageToSelected() { const value=$("#bulk-stage-input").value.trim(); if (!value || !state.selected.size) return; const orders=[...state.selected]; try { await Promise.all(orders.map((no)=>api(`/api/orders/${encodeURIComponent(no)}`,{method:"PATCH",body:JSON.stringify({custom_stage:value})}))); showToast(`已更新 ${orders.length} 条订单的处理阶段`); $("#bulk-stage-input").value=""; await loadOrders(); } catch(e){showToast(e.message,"error");} }
  async function applyCompletionToSelected() { const orderNos = [...state.selected]; if (!orderNos.length) return; if (!window.confirm(`确定将选中的 ${orderNos.length} 条订单标记为处理完成吗？`)) return; const button = $("#quick-complete"); setBusy(button, true); try { await Promise.all(orderNos.map((orderNo) => api(`/api/orders/${encodeURIComponent(orderNo)}`, { method: "PATCH", body: JSON.stringify({ stage: "COMPLETED", custom_stage: null }) }))); state.selected.clear(); showToast(`已将 ${orderNos.length} 条订单标记为处理完成`); await loadOrders(); } catch (error) { showToast(error.message, "error"); } finally { setBusy(button, false); updateSelectionUI(); } }
  async function saveTracking() { const button = $("#save-tracking"); setBusy(button, true); try { const orderNo = state.detail.order_no; await api(`/api/orders/${encodeURIComponent(orderNo)}/tracking`, { method: "POST", body: JSON.stringify({ actual_tracking_number: $("#tracking-input").value.trim() }) }); showToast("物流单号已保存"); await refreshOpenOrder(orderNo); } catch (error) { showToast(error.message, "error"); } finally { setBusy(button, false); } }
  async function confirmReturn() { try { const orderNo = state.detail.order_no; await api(`/api/orders/${encodeURIComponent(orderNo)}/return-confirmation` , { method: "POST" }); showToast("已记录回传店铺，订单完成"); await refreshOpenOrder(orderNo); } catch (error) { showToast(error.message, "error"); } }
  async function completeException() { try { const orderNo = state.detail.order_no; await api(`/api/orders/${encodeURIComponent(orderNo)}/complete`, { method: "POST", body: JSON.stringify({ processing_result: $("#exception-result").value, processing_note: $("#exception-note").value.trim() }) }); showToast("异常处理结果已保存"); await refreshOpenOrder(orderNo); } catch (error) { showToast(error.message, "error"); } }
  async function manualCheck() { const button = $("#manual-check"); setBusy(button, true); try { const result = await api("/api/reminders/check", { method: "POST" }); showToast(`提醒检查完成：生成 ${result.created}，投递 ${result.sent}`); if (state.detail) await openOrder(state.detail.order_no); } catch (error) { showToast(error.message, "error"); } finally { setBusy(button, false); } }
  async function testChannel(path, label) { try { const result = await api(path, { method: "POST" }); showToast(`${label}：${result.message || result.status}`, result.status === "SENT" ? "normal" : "error"); } catch (error) { showToast(error.message, "error"); } }
  function updateClock() { $("#current-clock").textContent = new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", dateStyle: "medium", timeStyle: "short" }).format(new Date()); }

  function hideUnusedDetailSections() { ["#tracking-input", "#exception-result", "#detail-platform"].forEach((selector) => { const section = $(selector)?.closest(".detail-section"); if (section) section.hidden = true; }); }
  function applySummaryFilter(filter) { state.summaryFilter = state.summaryFilter === filter ? "" : filter; $("#risk-filter").value = ""; state.selected.clear(); renderSummary(); renderTable(); }

  hideUnusedDetailSections();
  document.querySelectorAll("[data-summary-filter]").forEach((card) => { card.addEventListener("click", () => applySummaryFilter(card.dataset.summaryFilter)); card.addEventListener("keydown", (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); applySummaryFilter(card.dataset.summaryFilter); } }); });

  $("#import-trigger").addEventListener("click", () => $("#import-file").click()); $("#empty-import").addEventListener("click", () => $("#import-file").click()); $("#import-file").addEventListener("change", importWorkbook); $("#refresh-trigger").addEventListener("click", loadOrders); $("#settings-trigger").addEventListener("click", openSettings); $("#manual-check").addEventListener("click", manualCheck); ["#search-input", "#risk-filter"].forEach((selector) => $(selector).addEventListener("input", renderTable)); $("#select-all").addEventListener("change", (event) => { filteredOrders().forEach((order) => event.target.checked ? state.selected.add(order.order_no) : state.selected.delete(order.order_no)); state.selectionAnchor = event.target.checked && filteredOrders().length ? filteredOrders()[0].order_no : null; renderTable(); }); $("#delete-selected").addEventListener("click", () => deleteOrders([...state.selected])); $("#quick-today").addEventListener("click", () => applyModeToSelected("TODAY")); $("#quick-tomorrow").addEventListener("click", () => applyModeToSelected("TOMORROW")); $("#quick-long-term").addEventListener("click", () => applyModeToSelected("LONG_TERM")); $("#quick-unscheduled").addEventListener("click", () => applyModeToSelected("UNSCHEDULED")); $("#quick-complete").addEventListener("click", applyCompletionToSelected); $("#copy-selected").addEventListener("click", () => copyOrderNos([...state.selected])); $("#bulk-stage-save").addEventListener("click", applyCustomStageToSelected);
  $("#reminder-mode-input").addEventListener("change", (event) => { if (["TODAY", "TOMORROW"].includes(event.target.value)) $("#deadline-override-input").value = quickDeadlineInput(event.target.value); });
  $("#order-table-wrap").addEventListener("click", (event) => { const checkbox = event.target.closest(".row-checkbox"); if (checkbox) { const orderNo = checkbox.dataset.orderNo; const rows = filteredOrders(); const currentIndex = rows.findIndex((order) => order.order_no === orderNo); const anchorIndex = state.selectionAnchor ? rows.findIndex((order) => order.order_no === state.selectionAnchor) : -1; const nextChecked = checkbox.checked; if (event.shiftKey && anchorIndex >= 0 && currentIndex >= 0) { rows.slice(Math.min(anchorIndex, currentIndex), Math.max(anchorIndex, currentIndex) + 1).forEach((order) => nextChecked ? state.selected.add(order.order_no) : state.selected.delete(order.order_no)); checkbox.checked = nextChecked; renderTable(); } else { nextChecked ? state.selected.add(orderNo) : state.selected.delete(orderNo); state.selectionAnchor = orderNo; checkbox.checked = nextChecked; updateSelectionUI(); } return; } if (event.target.closest("select,input,textarea")) return; const copyButton = event.target.closest("[data-copy-order]"); if (copyButton) { event.stopPropagation(); copyOrderNos([copyButton.dataset.copyOrder]); return; } const deleteButton = event.target.closest("[data-delete-order]"); if (deleteButton) { event.stopPropagation(); deleteOrders([deleteButton.dataset.deleteOrder]); return; } const row = event.target.closest("tr"); if (row) openOrder(row.dataset.orderNo); });
  $("#drawer-close").addEventListener("click", closeDrawer); $("#drawer-backdrop").addEventListener("click", closeDrawer); $("#save-dates").addEventListener("click", saveDates); $("#save-custom-stage").addEventListener("click", saveCustomStage); $("#save-tracking").addEventListener("click", saveTracking); $("#confirm-return").addEventListener("click", confirmReturn); $("#complete-exception").addEventListener("click", completeException); $("#settings-close").addEventListener("click", closeSettings); $("#settings-dialog").addEventListener("click", (event) => { if (event.target === $("#settings-dialog")) closeSettings(); }); $("#settings-form").addEventListener("submit", saveSettings); $("#test-email").addEventListener("click", () => testChannel("/api/settings/test-email", "测试邮件")); $("#test-notification").addEventListener("click", () => testChannel("/api/settings/test-notification", "测试桌面通知")); document.addEventListener("keydown", (event) => { if (event.key === "Escape") { if (!$("#settings-dialog").hidden) closeSettings(); else if ($("#order-drawer").classList.contains("open")) closeDrawer(); } });

  updateClock(); window.setInterval(updateClock, 30000); loadSettings(); loadOrders(); startClientLifecycle();
})();
