(() => {
  "use strict";
  const $ = (selector) => document.querySelector(selector);
  const state = { orders: [], settings: {}, detail: null, toastTimer: null };
  const stageNames = { NEEDS_ARRIVAL_DATE: "待补到货日期", VIRTUAL_PENDING: "店铺虚发", WAITING_EXCEPTION: "等货 / 异常", SHIPPED_PENDING_RETURN: "待回传物流号", COMPLETED: "已完成" };
  const riskNames = { NORMAL: "正常", OVERDUE_RISK: "日期有风险", OVERDUE: "已逾期" };
  const issueNames = { MISSING_ARRIVAL: "缺少最晚到货时间", DATE_CONFLICT: "日期冲突", NONE: "自动计算" };
  async function api(path, options = {}) {
    const headers = { ...(options.headers || {}) };
    if (options.body && !(options.body instanceof FormData) && !headers["Content-Type"]) headers["Content-Type"] = "application/json";
    const response = await fetch(path, { ...options, headers });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(body.detail || body.message || `请求失败（${response.status}）`);
    return body;
  }
  function setText(selector, value) { $(selector).textContent = value == null || value === "" ? "—" : String(value); }
  function formatDate(value) { return value ? String(value).replace("T", " ").replace(/\+08:00$/, "").slice(0, 16) : "—"; }
  function inputDate(value) { return value ? String(value).replace("+08:00", "").slice(0, 16) : ""; }
  function apiDate(value) { return value ? value.replace("T", " ").slice(0, 16) : null; }
  function dateKey(value) { return value ? String(value).slice(0, 10) : ""; }
  function shanghaiToday() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai" }).format(new Date()); }
  function addCalendarDays(value, days) { if (!value) return ""; const date = new Date(`${value}T00:00:00+08:00`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
  function isUnfinished(order) { return order.stage !== "COMPLETED"; }
  function dueToday(order) { if (!isUnfinished(order)) return false; const today = shanghaiToday(); return (["VIRTUAL_PENDING", "WAITING_EXCEPTION"].includes(order.stage) && dateKey(order.deadline_override_at || order.deadline_at) === today) || dateKey(order.latest_arrival_at) === today || addCalendarDays(dateKey(order.latest_arrival_at), -1) === today; }
  function stageName(value) { return stageNames[value] || value || "—"; }
  function riskName(value) { return riskNames[value] || value || "正常"; }
  function issueName(value) { return issueNames[value] || value || "—"; }
  function showToast(message, kind = "normal") { const toast = $("#toast"); toast.textContent = message; toast.className = `toast ${kind}`; toast.hidden = false; window.clearTimeout(state.toastTimer); state.toastTimer = window.setTimeout(() => { toast.hidden = true; }, 4200); }
  function setBusy(button, busy) { if (button) { button.disabled = busy; button.dataset.busy = busy ? "true" : "false"; } }
  function filteredOrders() { const search = $("#search-input").value.trim().toLowerCase(); const stage = $("#stage-filter").value; const risk = $("#risk-filter").value; const erp = $("#erp-filter").value.trim().toLowerCase(); return state.orders.filter((order) => { const searchable = [order.order_no, order.platform_user_name, order.consignee_name].join(" ").toLowerCase(); return (!search || searchable.includes(search)) && (!stage || order.stage === stage) && (!risk || order.risk === risk) && (!erp || String(order.erp_status || "").toLowerCase().includes(erp)); }); }
  function renderSummary() { const unfinished = state.orders.filter(isUnfinished); setText("#summary-total", unfinished.length); setText("#summary-today", unfinished.filter(dueToday).length); setText("#summary-overdue", unfinished.filter((order) => order.risk === "OVERDUE").length); setText("#summary-missing", unfinished.filter((order) => order.deadline_issue === "MISSING_ARRIVAL").length); }
  function cell(value, className = "") { const node = document.createElement("td"); node.className = className; node.textContent = value == null || value === "" ? "—" : String(value); return node; }
  function renderTable() {
    const body = $("#order-table-body"); body.replaceChildren(); const rows = filteredOrders(); $("#result-count").textContent = `${rows.length} 条记录`;
    rows.forEach((order) => { const row = document.createElement("tr"); row.dataset.orderNo = order.order_no; row.tabIndex = 0; const orderCell = document.createElement("td"); orderCell.className = "order-cell"; const number = document.createElement("strong"); number.textContent = order.order_no || "—"; const buyer = document.createElement("span"); buyer.textContent = order.consignee_name || order.platform_user_name || "未填写收件人"; orderCell.append(number, buyer); row.append(orderCell); row.append(cell(`${order.platform_user_name || "未命名店铺"} / ${order.warehouse_name || "未分配仓库"}`, "muted-cell"), cell(stageName(order.stage), "stage-cell"), cell(formatDate(order.latest_ship_at), "date-cell"), cell(formatDate(order.latest_arrival_at), "date-cell"), cell(formatDate(order.deadline_override_at || order.deadline_at), "date-cell deadline-cell")); const riskCell = document.createElement("td"); const risk = document.createElement("span"); risk.className = `risk-badge risk-${String(order.risk || "NORMAL").toLowerCase()}`; risk.textContent = riskName(order.risk); riskCell.append(risk); row.append(riskCell); const actionCell = document.createElement("td"); actionCell.className = "action-cell"; const action = document.createElement("button"); action.type = "button"; action.className = "row-action"; action.textContent = "查看"; action.title = `查看 ${order.order_no}`; actionCell.append(action); row.append(actionCell); body.append(row); });
    const empty = $("#empty-state"); empty.hidden = rows.length !== 0; $("#order-table").hidden = rows.length === 0; $("#empty-title").textContent = state.orders.length ? "没有匹配订单" : "暂无订单记录"; $("#empty-copy").textContent = state.orders.length ? "调整筛选条件，或清空搜索词后再试。" : "导入 ERP 导出的 Excel 后，订单会出现在这里。"; $("#empty-import").hidden = Boolean(state.orders.length);
  }
  async function loadOrders() { $("#loading-state").hidden = false; try { const data = await api("/api/orders?limit=500"); state.orders = data.orders || []; renderSummary(); renderTable(); $("#service-status").textContent = "本机服务运行中"; } catch (error) { $("#service-status").textContent = "服务连接异常"; showToast(error.message, "error"); } finally { $("#loading-state").hidden = true; } }
  function explanation(order) { if (order.deadline_issue === "MISSING_ARRIVAL") return "还没有填写最晚到货时间，系统暂不生成提醒。请补充到货时间后保存。"; if (order.deadline_issue === "DATE_CONFLICT") return "到货时间 - 4 天早于最晚发货时间，且发货日补偿后又超过最晚到货时间。请手动填写一个不晚于到货时间的处理截止。"; if (order.deadline_rule === "MANUAL") return `当前使用手动截止 ${formatDate(order.deadline_override_at)}，它不晚于最晚到货时间。`; if (order.deadline_rule === "SHIP_PLUS_2" || order.deadline_rule === "SHIP_PLUS_3") return `到货时间 - 4 天早于最晚发货时间，因此使用最晚发货时间 + ${order.deadline_rule.endsWith("3") ? "3" : "2"} 天计算。`; return "处理截止按最晚到货时间往前 4 天计算，系统会在处理日、到货前一天和到货日 10:00 汇总提醒。"; }
  function renderDetail(detail) {
    const order = detail.order; state.detail = order; $("#drawer-title").textContent = order.order_no || "订单详情"; $("#drawer-subtitle").textContent = `${order.platform_user_name || "未命名店铺"} · ${order.consignee_name || "未填写收件人"}`; setText("#detail-stage", stageName(order.stage)); const risk = $("#detail-risk"); risk.textContent = riskName(order.risk); risk.className = `risk-badge risk-${String(order.risk || "NORMAL").toLowerCase()}`; setText("#detail-rule", issueName(order.deadline_issue) + (order.deadline_rule && order.deadline_rule !== "NONE" ? ` · ${order.deadline_rule}` : "")); setText("#detail-date-explanation", explanation(order)); $("#arrival-input").value = inputDate(order.latest_arrival_at); $("#deadline-override-input").value = inputDate(order.deadline_override_at); $("#tracking-input").value = order.actual_tracking_number || ""; $("#exception-note").value = order.processing_note || ""; setText("#tracking-status", order.return_confirmed_at ? `已于 ${formatDate(order.return_confirmed_at)} 确认回传店铺` : order.actual_tracking_number ? "已有实际物流单号，等待确认回传" : "尚未取得实际物流单号"); setText("#detail-erp-status", order.erp_status); setText("#detail-platform", `${order.platform_user_name || "—"} / ${order.platform_seller_id || "—"}`); setText("#detail-warehouse", order.warehouse_name); setText("#detail-consignee", order.consignee_name); setText("#detail-country", order.consignee_country_name); setText("#detail-shipping", order.shipping_method_name_cn || order.shipping_method_name_en); setText("#detail-erp-tracking", order.erp_tracking_number);
    const resultSelect = $("#exception-result"); resultSelect.replaceChildren(); const blank = document.createElement("option"); blank.value = ""; blank.textContent = "选择结果"; resultSelect.append(blank); const results = state.settings.processing_results?.length ? state.settings.processing_results : ["取消", "等待补货", "继续等待"]; results.forEach((value) => { const option = document.createElement("option"); option.value = value; option.textContent = value; resultSelect.append(option); }); resultSelect.value = order.processing_result || ""; renderReminders(detail.reminders || []); renderHistory(detail.activity || []); updateDetailControls(order); const alert = $("#detail-alert"); alert.hidden = !["MISSING_ARRIVAL", "DATE_CONFLICT"].includes(order.deadline_issue); alert.textContent = order.deadline_issue === "MISSING_ARRIVAL" ? "请先补充最晚到货时间，系统才会安排提醒。" : "日期存在冲突，请手动设置处理截止时间。";
  }
  function updateDetailControls(order) { const completed = order.stage === "COMPLETED"; ["#save-dates", "#save-tracking", "#confirm-return", "#complete-exception"].forEach((selector) => { $(selector).disabled = completed; }); $("#confirm-return").disabled = completed || !order.actual_tracking_number; }
  function renderReminders(reminders) { const list = $("#detail-reminders"); list.replaceChildren(); if (!reminders.length) { const empty = document.createElement("span"); empty.className = "muted"; empty.textContent = "还没有生成提醒事件"; list.append(empty); return; } reminders.slice(0, 8).forEach((event) => { const item = document.createElement("div"); item.className = "reminder-item"; const label = document.createElement("strong"); label.textContent = event.event_type; const meta = document.createElement("span"); meta.textContent = `${formatDate(event.scheduled_at)} · ${event.status || "PENDING"}`; item.append(label, meta); list.append(item); }); }
  function renderHistory(history) { const list = $("#detail-history"); list.replaceChildren(); if (!history.length) { const empty = document.createElement("li"); empty.className = "muted"; empty.textContent = "暂无操作记录"; list.append(empty); return; } history.slice(0, 12).forEach((entry) => { const item = document.createElement("li"); const action = document.createElement("strong"); action.textContent = entry.action || "操作"; const meta = document.createElement("span"); meta.textContent = `${formatDate(entry.created_at)} · ${entry.actor || "本机"}`; item.append(action, meta); list.append(item); }); }
  async function openOrder(orderNo) { try { const detail = await api(`/api/orders/${encodeURIComponent(orderNo)}`); $("#order-drawer").classList.add("open"); $("#order-drawer").setAttribute("aria-hidden", "false"); $("#drawer-backdrop").hidden = false; document.body.classList.add("drawer-open"); renderDetail(detail); $("#drawer-close").focus(); } catch (error) { showToast(error.message, "error"); } }
  function closeDrawer() { $("#order-drawer").classList.remove("open"); $("#order-drawer").setAttribute("aria-hidden", "true"); $("#drawer-backdrop").hidden = true; document.body.classList.remove("drawer-open"); state.detail = null; }
  function openSettings() { $("#settings-dialog").hidden = false; document.body.classList.add("modal-open"); $("#setting-compensation").focus(); }
  function closeSettings() { $("#settings-dialog").hidden = true; document.body.classList.remove("modal-open"); }
  function renderSettings() { const settings = state.settings; $("#setting-compensation").value = String(settings.compensation_days || 2); $("#setting-windows").checked = settings.windows_notifications_enabled !== false; $("#setting-email").checked = settings.email_enabled === true; $("#setting-smtp-host").value = settings.smtp_host || ""; $("#setting-smtp-port").value = settings.smtp_port || 587; $("#setting-smtp-username").value = settings.smtp_username || ""; $("#setting-recipients").value = (settings.recipients || []).join(", "); $("#setting-results").value = (settings.processing_results || []).join(", "); }
  async function loadSettings() { try { state.settings = await api("/api/settings"); renderSettings(); } catch (error) { showToast(error.message, "error"); } }
  async function saveSettings(event) { event.preventDefault(); const button = $("#settings-form button[type=submit]"); setBusy(button, true); const patch = { compensation_days: Number($("#setting-compensation").value), windows_notifications_enabled: $("#setting-windows").checked, email_enabled: $("#setting-email").checked, smtp_host: $("#setting-smtp-host").value.trim(), smtp_port: Number($("#setting-smtp-port").value), smtp_username: $("#setting-smtp-username").value.trim(), recipients: $("#setting-recipients").value.split(",").map((item) => item.trim()).filter(Boolean), processing_results: $("#setting-results").value.split(",").map((item) => item.trim()).filter(Boolean) }; const secret = $("#setting-smtp-secret").value; if (secret) patch.smtp_authorization_code = secret; try { state.settings = await api("/api/settings", { method: "PATCH", body: JSON.stringify(patch) }); $("#setting-smtp-secret").value = ""; $("#settings-feedback").textContent = "已保存"; showToast("提醒设置已保存"); } catch (error) { $("#settings-feedback").textContent = error.message; showToast(error.message, "error"); } finally { setBusy(button, false); } }
  async function importWorkbook(event) { const file = event.target.files[0]; if (!file) return; const button = $("#import-trigger"); setBusy(button, true); const form = new FormData(); form.append("file", file); try { const result = await api("/api/import", { method: "POST", headers: {}, body: form }); showToast(`导入完成：新增 ${result.added}，更新 ${result.updated}，重复 ${result.duplicates || 0}`); await loadOrders(); } catch (error) { showToast(error.message, "error"); } finally { event.target.value = ""; setBusy(button, false); } }
  async function saveDates() { const button = $("#save-dates"); setBusy(button, true); try { const result = await api(`/api/orders/${encodeURIComponent(state.detail.order_no)}`, { method: "PATCH", body: JSON.stringify({ latest_arrival_at: apiDate($("#arrival-input").value), deadline_override_at: apiDate($("#deadline-override-input").value) }) }); state.detail = result.order; renderDetail({ order: result.order, activity: [], reminders: [] }); showToast("日期已保存"); await loadOrders(); } catch (error) { showToast(error.message, "error"); } finally { setBusy(button, false); } }
  async function saveTracking() { const button = $("#save-tracking"); setBusy(button, true); try { const result = await api(`/api/orders/${encodeURIComponent(state.detail.order_no)}/tracking`, { method: "POST", body: JSON.stringify({ actual_tracking_number: $("#tracking-input").value.trim() }) }); state.detail = result.order; renderDetail({ order: result.order, activity: [], reminders: [] }); showToast("物流单号已保存，订单进入待回传阶段"); await loadOrders(); } catch (error) { showToast(error.message, "error"); } finally { setBusy(button, false); } }
  async function confirmReturn() { try { const result = await api(`/api/orders/${encodeURIComponent(state.detail.order_no)}/return-confirmation`, { method: "POST" }); state.detail = result.order; renderDetail({ order: result.order, activity: [], reminders: [] }); showToast("已记录回传店铺，订单完成"); await loadOrders(); } catch (error) { showToast(error.message, "error"); } }
  async function completeException() { try { const result = await api(`/api/orders/${encodeURIComponent(state.detail.order_no)}/complete`, { method: "POST", body: JSON.stringify({ processing_result: $("#exception-result").value, processing_note: $("#exception-note").value.trim() }) }); state.detail = result.order; renderDetail({ order: result.order, activity: [], reminders: [] }); showToast("异常处理结果已保存"); await loadOrders(); } catch (error) { showToast(error.message, "error"); } }
  async function manualCheck() { const button = $("#manual-check"); setBusy(button, true); try { const result = await api("/api/reminders/check", { method: "POST" }); showToast(`提醒检查完成：生成 ${result.created}，投递 ${result.sent}`); if (state.detail) openOrder(state.detail.order_no); } catch (error) { showToast(error.message, "error"); } finally { setBusy(button, false); } }
  async function testChannel(path, label) { try { const result = await api(path, { method: "POST" }); showToast(`${label}：${result.message || result.status}`, result.status === "SENT" ? "normal" : "error"); } catch (error) { showToast(error.message, "error"); } }
  function updateClock() { $("#current-clock").textContent = new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", dateStyle: "medium", timeStyle: "short" }).format(new Date()); }
  $("#import-trigger").addEventListener("click", () => $("#import-file").click()); $("#empty-import").addEventListener("click", () => $("#import-file").click()); $("#import-file").addEventListener("change", importWorkbook); $("#refresh-trigger").addEventListener("click", loadOrders); $("#settings-trigger").addEventListener("click", openSettings); $("#manual-check").addEventListener("click", manualCheck); ["#search-input", "#stage-filter", "#risk-filter", "#erp-filter"].forEach((selector) => $(selector).addEventListener("input", renderTable)); $("#order-table-body").addEventListener("click", (event) => { const row = event.target.closest("tr"); if (row) openOrder(row.dataset.orderNo); }); $("#order-table-body").addEventListener("keydown", (event) => { if (event.key === "Enter") { const row = event.target.closest("tr"); if (row) openOrder(row.dataset.orderNo); } }); $("#drawer-close").addEventListener("click", closeDrawer); $("#drawer-backdrop").addEventListener("click", closeDrawer); $("#save-dates").addEventListener("click", saveDates); $("#save-tracking").addEventListener("click", saveTracking); $("#confirm-return").addEventListener("click", confirmReturn); $("#complete-exception").addEventListener("click", completeException); $("#settings-close").addEventListener("click", closeSettings); $("#settings-dialog").addEventListener("click", (event) => { if (event.target === $("#settings-dialog")) closeSettings(); }); $("#settings-form").addEventListener("submit", saveSettings); $("#test-email").addEventListener("click", () => testChannel("/api/settings/test-email", "测试邮件")); $("#test-notification").addEventListener("click", () => testChannel("/api/settings/test-notification", "测试桌面通知")); document.addEventListener("keydown", (event) => { if (event.key === "Escape") { if (!$("#settings-dialog").hidden) closeSettings(); else if ($("#order-drawer").classList.contains("open")) closeDrawer(); } }); updateClock(); window.setInterval(updateClock, 30000); loadSettings(); loadOrders();
})();
